[package]
name = "cli_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
arc-swap = "1.7.1"
axum = "0.8.1"
clap = "4.5.24"
config = "0.15.4"
dotenv = "0.15.0"
serde ={version= "1.0.217",features=["derive"]}
tokio = {version="1.42.0",features=["full"]}
